# Generated by Django 3.2.5 on 2022-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220801_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('period', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
