# Generated by Django 3.2.5 on 2022-08-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220801_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectHours',
            new_name='ProjectHour',
        ),
    ]
