# Generated by Django 3.2.5 on 2022-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_projecthours_projecthour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
