# Generated by Django 3.2.5 on 2022-08-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectmember', to='projects.project'),
            preserve_default=False,
        ),
    ]
