# Generated by Django 3.2.5 on 2022-08-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectmember_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthour',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecthour',
            name='projectmember',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='projects.projectmember'),
            preserve_default=False,
        ),
    ]
