# Generated by Django 3.2.5 on 2022-08-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220803_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'customer')},
        ),
    ]
