# Generated by Django 3.2.5 on 2022-08-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
