# Generated by Django 3.2.5 on 2022-08-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0013_auto_20220808_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecthour',
            unique_together={('member', 'project', 'week')},
        ),
    ]
