# Generated by Django 3.2.5 on 2022-08-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projecthour_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectimage',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
